name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Configure Laravel Nova Access
      run: composer config http-basic.nova.laravel.com ${{NOVA_USERNAME}} ${{NOVA_PASSWORD}}
      env:
        NOVA_USERNAME: hendrik.mennen@mennen.online
        NOVA_PASSWORD: mennen-1T
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        LEXOFFICE_ACCESS_TOKEN: 0ff74fcd-bd92-4eb2-bcd6-1fc43d1768dc
      run: vendor/bin/phpunit
    - name: Import Lexoffice Contacts
      run: php artisan lexoffice:contacts:sync
    - name: Import Lexoffice Invoices
      run: php artisan lexoffice:invoice:sync
